apiVersion: v1
kind: Service
metadata:
  name: wiki
  labels:
    name: wiki
spec:
  type: NodePort 
  ports:
    - port: 8042 
      targetPort: 8042
      nodePort: 30042
      protocol: TCP
  selector:
    name: wiki
